[project]
name = "pesquisa-dask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "ipykernel",
    "dask",
    "dask-cuda",
    "nvidia-ml-py",
    "pyarrow>=13.0.0",
    "requests",
    "aiohttp",
    "dask-ml>=2025.1.0",
    "torch",
    "skorch"
]
